name: shop
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  gap: ^3.0.1
  flutter_svg: ^2.0.10+1
  pelaicons: ^0.0.1
  smooth_page_indicator: ^1.2.0+3
  dotted_dashed_line: ^0.0.3
  persian_number_utility: ^1.1.4
  awesome_icons: ^1.1.0
  dartz: ^0.10.1
  shared_preferences: ^2.3.1
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  get_it: ^7.7.0
  cached_network_image: ^3.4.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  dio: ^5.5.0+1
  flutter_spinkit: ^5.2.1
  logger: ^2.4.0
  fluttertoast: ^8.2.8
  flutter_native_splash: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.11

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/gifs/

  fonts:
    - family: GR
      fonts:
        - asset: assets/fonts/GilroyRegular.ttf
          weight: 400

    - family: GM
      fonts:
        - asset: assets/fonts/GilroyMedium.ttf
          weight: 500

    - family: GB
      fonts:
        - asset: assets/fonts/GilroyBold.ttf
          weight: 700

    - family: GEB
      fonts:
        - asset: assets/fonts/GilroyExtraBold.ttf
          weight: 800

    - family: GH
      fonts:
        - asset: assets/fonts/GilroyHeavy.ttf
          weight: 900

    - family: SM
      fonts:
        - asset: assets/fonts/ShabnamMedium.ttf
          weight: 500

    - family: SB
      fonts:
        - asset: assets/fonts/ShabnamBold.ttf
          weight: 700

    - family: dana
      fonts:
        - asset: assets/fonts/dana.ttf
          weight: 500

flutter_native_splash:
  android: true
  ios: true
  web: false
  image: assets/images/logo_spash.png
  color: "#3B5EDF"

  image_dark: assets/images/logo_spash.png
  color_dark: "#3B5EDF"

  android_12:
    image: assets/images/logo_spash.png
    color: "#3B5EDF"

    image_dark: assets/images/logo_spash.png
    color_dark: "#3B5EDF"
    android_gravity: contain
